"""Market Profile primitives, checked against hand-computed profiles.

The fixtures are small enough to verify with a pencil, which is the only way to
trust a value area: the algorithm has two accepted variants and a golden file
generated by our own code would prove nothing.
"""
import pytest

from pipeline.profile import tpo as MP


def bars(*ranges, vol=None):
    return [{"low": lo, "high": hi, "volume": (vol[i] if vol else 100)}
            for i, (lo, hi) in enumerate(ranges)]


# ------------------------------------------------------------- bucketing

def test_buckets_align_to_the_tick_grid_not_to_the_bar():
    # 101.3-102.7 on a 1.0 grid must be 101,102,103 -- NOT 101.3,102.3.
    # If it aligned to the bar, no two bars would ever share a price and every
    # profile would be flat.
    assert MP.price_buckets(101.3, 102.7, 1.0) == [101.0, 102.0, 103.0]


def test_two_overlapping_bars_stack_on_the_same_price():
    prof = MP.build_profile(bars((100, 102), (101, 103)), tick=1.0)
    assert prof[101.0] == "AB" and prof[102.0] == "AB"
    assert prof[100.0] == "A" and prof[103.0] == "B"


def test_a_price_revisited_inside_one_bracket_earns_one_letter():
    # TPO counts periods, not touches.
    prof = MP.build_profile(bars((100, 100)), tick=1.0)
    assert prof[100.0] == "A"


# ------------------------------------------------------------------ POC

def test_poc_is_the_most_occupied_price():
    prof = MP.build_profile(bars((100, 103), (101, 102), (101, 102)), tick=1.0)
    assert MP.poc(MP.tpo_counts(prof)) in (101.0, 102.0)


def test_poc_ties_resolve_toward_the_middle_of_the_range():
    # 100 and 104 both have 1 TPO; 102 sits in the middle with 1 too.
    counts = {100.0: 1, 102.0: 1, 104.0: 1}
    assert MP.poc(counts) == 102.0


def test_poc_of_an_empty_profile_is_none_not_zero():
    assert MP.poc({}) is None


# ----------------------------------------------------------- value area

def _sym():
    # A symmetric profile: 20 TPOs total, POC at 103 with 6.
    return {100.0: 1, 101.0: 2, 102.0: 4, 103.0: 6, 104.0: 4, 105.0: 2, 106.0: 1}


def test_value_area_covers_at_least_the_target():
    va = MP.value_area(_sym())
    assert va["covered"] >= 0.70
    assert va["low"] <= va["poc"] <= va["high"]


def test_the_pair_method_overshoots_and_that_is_correct_behaviour():
    # Hand-computed on _sym() (total 20 TPOs, target 14, POC 103 with 6):
    #   pair:   up[104,105]=6 vs dn[101,102]=6 -> tie goes up, acc 12
    #           up[106]=1     vs dn[101,102]=6 -> down, acc 18  => 101-105, 90%
    # Absorbing two prices at a time necessarily overshoots. On a real profile
    # with 50+ levels the excess is one level's worth; on a 7-level toy it is
    # glaring, which is exactly why the toy is the right place to pin it down.
    va = MP.value_area(_sym(), method="pair")
    assert (va["low"], va["high"]) == (101.0, 105.0)
    assert va["covered"] == pytest.approx(0.90)


def test_the_single_method_lands_exactly_on_the_target_here():
    #   single: up[104]=4 vs dn[102]=4 -> tie goes up, acc 10
    #           up[105]=2 vs dn[102]=4 -> down,        acc 14  => 102-104, 70%
    va = MP.value_area(_sym(), method="single")
    assert (va["low"], va["high"]) == (102.0, 104.0)
    assert va["covered"] == pytest.approx(0.70)


def test_the_two_methods_disagree_on_the_same_profile():
    # The headline reason `method` is carried in the result. A value area quoted
    # without it is not reproducible, and the gap here is two full price levels.
    pair = MP.value_area(_sym(), method="pair")
    single = MP.value_area(_sym(), method="single")
    assert (pair["low"], pair["high"]) != (single["low"], single["high"])


def test_the_two_published_methods_can_disagree_and_both_are_reported():
    # A profile where absorbing a PAIR overshoots what ONE price would have taken.
    counts = {100.0: 1, 101.0: 1, 102.0: 5, 103.0: 1, 104.0: 4}
    pair = MP.value_area(counts, method="pair")
    single = MP.value_area(counts, method="single")
    assert pair["method"] == "pair" and single["method"] == "single"
    # Whatever they return, each must be self-consistent and hit the target.
    for va in (pair, single):
        assert va["covered"] >= 0.70


def test_value_area_rejects_an_unknown_method():
    with pytest.raises(ValueError, match="method"):
        MP.value_area(_sym(), method="whatever-my-vendor-does")


def test_an_exhausted_side_never_wins_a_zero_to_zero_tie():
    # POC sits on the bottom price, so `dn` is empty forever. An empty side
    # summing to 0 must not beat a real side also summing to 0, and must not
    # index off the end. total 8, target 5.6, POC 100 with 5 -> must expand up.
    counts = {100.0: 5, 101.0: 1, 102.0: 1, 103.0: 1}
    va = MP.value_area(counts)
    assert va["low"] == 100.0 and va["high"] == 102.0
    assert va["covered"] >= 0.70


# ------------------------------------------------- singles, tails, extremes

def test_single_prints_are_the_one_bracket_prices():
    prof = MP.build_profile(bars((100, 102), (101, 103)), tick=1.0)
    assert MP.single_prints(prof) == [100.0, 103.0]


def test_a_one_tick_tail_is_reported_but_flagged_insignificant():
    # Dalton wants two TPOs before a tail means anything; near-misses stay visible.
    prof = MP.build_profile(bars((100, 102), (101, 103)), tick=1.0)
    t = MP.tails(prof)
    assert t["buying"]["length"] == 1 and t["buying"]["significant"] is False


def test_a_multi_tick_tail_is_significant():
    prof = MP.build_profile(bars((100, 105), (103, 105), (103, 105)), tick=1.0)
    t = MP.tails(prof)
    assert t["buying"]["length"] == 3          # 100,101,102 are single prints
    assert t["buying"]["significant"] is True


def test_poor_high_is_an_extreme_that_kept_trading():
    prof = MP.build_profile(bars((100, 105), (104, 105)), tick=1.0)
    pe = MP.poor_extremes(prof)
    assert pe["poor_high"] is True and pe["high_tpos"] == 2
    assert pe["poor_low"] is False


def test_initial_balance_is_the_first_two_brackets():
    ib = MP.initial_balance(bars((100, 102), (99, 103), (95, 110)))
    assert (ib["low"], ib["high"]) == (99.0, 103.0)


# -------------------------------------------------------- volume at price

def test_bar_volume_is_spread_across_the_prices_it_spans():
    vap = MP.volume_at_price(bars((100, 102), vol=[300]), tick=1.0)
    assert vap[100.0] == vap[101.0] == vap[102.0] == 100.0


def test_vpoc_and_poc_need_not_be_the_same_price():
    # Time piles at 101; volume piles at 105 in one fast bar.
    b = bars((101, 101), (101, 101), (101, 101), (105, 105), vol=[1, 1, 1, 900])
    prof = MP.build_profile(b, tick=1.0)
    assert MP.poc(MP.tpo_counts(prof)) == 101.0
    assert MP.vpoc(MP.volume_at_price(b, tick=1.0)) == 105.0


def test_volume_without_time_finds_the_traded_but_unaccepted_price():
    b = bars((101, 101), (101, 101), (101, 101), (105, 105), vol=[1, 1, 1, 900])
    prof = MP.build_profile(b, tick=1.0)
    out = MP.volume_without_time(MP.volume_at_price(b, 1.0), MP.tpo_counts(prof))
    assert 105.0 in out and 101.0 not in out
